id: IA970B393
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-03-29T16:41:35+00:00'
last_modified: '2022-06-16T05:09:21.523660+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22704
  title: བསྟན་འགྱུར ༼སྣར་ཐང༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F045:
      image_group_id: I3252
      title: ''
      total_pages: ''
      order: 1
      base_file: F045.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
